spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
  # 環境のProfileや application-<env>.ymlに影響
  #profiles.active: development

# 以下、設定値取得サンプル用
app:
  name: "sample"
  version: 0.0
  sample1controller:
    name: "Sample1 Application"
    version: 1.0
  sample2controller:
    name: "Sample2 Application"
    version: 2.0
  retrycontroller:
    maxAttempts: "2"
    delay: "300"

# logging.level.rootをDEBUGにすると非常に多くのSpring Bootのデバッグログまで出力されます。
# logging.levelにあるcom.example.demoはこのデモアプリケーションのクラスパスを指定しています。
# 設定項目参考: https://b1san-blog.com/post/spring/spring-log/
logging:
  level:
    root: INFO
    com.example.demo: debug
