cookie:
  secure: false
  max-age: 300

spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
  # 環境のProfileや application-<env>.ymlに影響
  #profiles.active: development
  security:
    oauth2:
      client:
        registration:
          idp:
            # 以下、テスト用
            client-id: test1
            client-secret: skes5xvkplk6vtfnj4unlxldvszxj5ao367qri3eahsn6hwszq
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
        provider:
          idp:
            issuer-uri: http://192.168.3.19:5556/dex


# 以下、設定値取得サンプル用
app:
  name: "sample"
  version: 0.0
  sample1controller:
    name: "Sample1 Application"
    version: 1.0
  sample2controller:
    name: "Sample2 Application"
    version: 2.0

# logging.level.rootをDEBUGにすると非常に多くのSpring Bootのデバッグログまで出力されます。
# logging.levelにあるcom.example.demoはこのデモアプリケーションのクラスパスを指定しています。
# 設定項目参考: https://b1san-blog.com/post/spring/spring-log/
logging:
  level:
    root: INFO
    com.example.demo: debug
